export const productList = {
  statusCode: 200,
  success: true,
  error: null,
  data: [
    {
      id: '20280',
      title: 'کره خانگی',
      price: '459490',
      productId: '5265564378350',
      description: 'تهیه شده از شیر تازه',
      categoryTitle: '',
      categoryId: '',
      imagePath: 'assets/public/images/products/homemade-butter.jpg',
      status: 'ended',
    },
    {
      id: '67181',
      title: 'شیر بادام خانگی',
      price: '415651',
      productId: '4564572119464',
      description: 'تهیه شده از شیر تازه',
      categoryTitle: '',
      categoryId: '',
      imagePath: 'assets/public/images/products/homem-made-almond-milk.jpg',
      status: 'avalable',
    },
    {
      id: '4690',
      title: 'شیر کاکائو خانگی',
      price: '430500',
      productId: '8904290526277',
      description: 'تهیه شده از شیر تازه',
      categoryTitle: '',
      categoryId: '',
      imagePath: 'assets/public/images/products/homem-made-coca-milk.jpg',
      status: 'ended',
    },
    {
      id: '22102',
      title: 'شیرعسل خانگی',
      price: '457380',
      productId: '3873181504507',
      description: 'تهیه شده از شیر تازه',
      categoryTitle: '',
      categoryId: '',
      imagePath: 'assets/public/images/products/homemade-Oat-Milk.jpg',
      status: 'ended',
    },
  ],
};
